/*
 * Vencord, a Discord client mod
 * Copyright (c) 2026 Giftedx
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

// GENERATED by scripts/build-index.mts — do not edit by hand.
//
// Provenance for kitchenIndex.b64, which holds the payload itself.
//
// Source:    https://raw.githubusercontent.com/xsalazar/emoji-kitchen-backend/9d2d8eb9281702bd7fdc3ee583a0fa49343a7ae7/app/metadata.json
// Source ref:9d2d8eb9281702bd7fdc3ee583a0fa49343a7ae7
// SHA-256:   73a7a2a6fbeb620f13ed6622b344cc0dfd21dfe07aca8ce46c564afe54e21804
// Emoji Kitchen artwork (c) Google. Pair metadata from xsalazar/emoji-kitchen.
// Contents:  emoji=619 pairs=147000 dates=43
// Size:      packed=783.3 KB gzip=375.4 KB

/** Upstream metadata commit the index was built from. */
export const INDEX_SOURCE_REF = "9d2d8eb9281702bd7fdc3ee583a0fa49343a7ae7";
/** Digest of that upstream metadata, as downloaded. */
export const INDEX_SOURCE_SHA256 = "73a7a2a6fbeb620f13ed6622b344cc0dfd21dfe07aca8ce46c564afe54e21804";
/** Digest of kitchenIndex.b64, checked after fetching so a bad payload cannot load. */
export const INDEX_SHA256 = "782b393c6da7a3dad8986a18a775ba56a29645d70b6e987ef8891c76381976e8";
