/*
 * Vencord, a Discord client mod
 * Copyright (c) 2026 Giftedx
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

/**
 * Regenerates twemojiParts.ts — the inventory of Twemoji face parts available
 * from Ryhon0/open-emoji-mash, used for the generated-mashup mode.
 *
 * Run manually:
 *   pnpm build-parts
 *
 * Unlike Emoji Kitchen (hand-drawn, 147k fixed pairs), these mashups are
 * composited at runtime from cut-up Twemoji: a base, one emoji's eyes and the
 * other's mouth. That only works for faces, so coverage is far smaller.
 */

import { writeFileSync } from "node:fs";

const REPO = "Ryhon0/open-emoji-mash";
const REF = "7eadca1844e5b2f932a2c90a09e3a47839d5b8c8"; // pinned; master moved would silently change part URLs
const OUT = "twemojiParts.ts";

/** jsDelivr's listing API — unauthenticated and not rate-limited, unlike GitHub's. */
async function listFiles(): Promise<string[]> {
    const res = await fetch(`https://data.jsdelivr.com/v1/packages/gh/${REPO}@${REF}?structure=flat`);
    if (!res.ok) throw new Error(`listing failed: ${res.status} ${res.statusText}`);

    const body = await res.json() as { files?: Array<{ name: string; }>; };
    if (!body.files?.length) throw new Error("jsDelivr returned no files");
    return body.files.map(f => f.name);
}

function svgsIn(files: string[], dir: string): string[] {
    const prefix = `/${dir}/`;
    return files
        .filter(f => f.startsWith(prefix) && f.endsWith(".svg") && !f.slice(prefix.length, -4).includes("/"))
        .map(f => f.slice(prefix.length, -4));
}

async function fetchBases(): Promise<Record<string, string>> {
    const res = await fetch(`https://cdn.jsdelivr.net/gh/${REPO}@${REF}/bases.json`);
    if (!res.ok) throw new Error(`bases.json failed: ${res.status}`);
    return await res.json() as Record<string, string>;
}

const [files, bases] = await Promise.all([listFiles(), fetchBases()]);

const eyes = svgsIn(files, "eyes");
const mouth = svgsIn(files, "mouth");
const base = svgsIn(files, "base");

// An emoji can contribute eyes and/or a mouth. It can only be used as the
// "shape" side if it also resolves to a base.
const eyeSet = new Set(eyes);
const mouthSet = new Set(mouth);
const baseSet = new Set(base);
const sharedBases = new Set(Object.values(bases));

const usable = [...new Set([...eyes, ...mouth])]
    .filter(cp => baseSet.has(cp) || cp in bases)
    .sort();

if (usable.length < 50) {
    throw new Error(`only ${usable.length} usable emoji — upstream layout probably changed`);
}
if (sharedBases.size === 0) {
    throw new Error("bases.json produced no shared base names");
}

writeFileSync(OUT,
    `/*
 * Vencord, a Discord client mod
 * Copyright (c) 2026 Giftedx
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

// GENERATED by scripts/build-parts.mts — do not edit by hand.
//
// Source: https://github.com/${REPO} (GPL-3.0), cut-up Twemoji face parts.
// Twemoji artwork (c) Twitter, CC-BY 4.0.
// Counts: eyes=${eyes.length} mouth=${mouth.length} base=${base.length} usable=${usable.length}

/** Pinned upstream revision. Part URLs are built against exactly this tree. */
export const PARTS_REF = "${REF}";
export const PARTS_BASE_URL = "https://cdn.jsdelivr.net/gh/${REPO}@${REF}";

/** Codepoints that can take part in a generated mashup. */
export const PART_EMOJI: readonly string[] = ${JSON.stringify(usable)};

/** Codepoints with an eyes/ asset. */
export const HAS_EYES: ReadonlySet<string> = new Set(${JSON.stringify(eyes)});

/** Codepoints with a mouth/ asset. */
export const HAS_MOUTH: ReadonlySet<string> = new Set(${JSON.stringify(mouth)});

/** Codepoints with their own base/ asset. */
export const HAS_OWN_BASE: ReadonlySet<string> = new Set(${JSON.stringify(base)});

/** Codepoint -> shared base name, for emoji without their own base. */
export const SHARED_BASE: Readonly<Record<string, string>> = ${JSON.stringify(bases)};
`);

console.log(`eyes=${eyes.length} mouth=${mouth.length} base=${base.length}`);
console.log(`shared bases: ${[...sharedBases].join(", ")}`);
console.log(`usable emoji: ${usable.length}`);
console.log(`wrote ${OUT}`);

